Jj create a category#10
NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls pull request #6
Opened 2022-11-01 14:01 UTC by jacobjjude

# Description

Added a Create A Category function. Users should be able to create their own category, which then gets added to the database and is available to add to Posts.

[Trello Card](https://trello.com/c/65tjvjmI)

# Testing Instructions

1. `git add` and `git commit` whatever you're working on on your branch
2. `git checkout main`
3. `git fetch --a`
4. `git checkout <JJ-CreateACategory#10>`
5. If you don't see the most recent version of my files, `git pull origin < JJ-CreateACategory#10>`
6. If you haven't created the Tabloid MVC database, please do so.
7. Use this data to fill out tables and columns: [SQL data](https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/01_TabloidMVC_Create_DB.sql)
8. Use this to seed the database : [SQL SEED DATA](https://github.com/NewForce-Cohort-6/tabloidmvc-the-tootsie-rolls/blob/main/SQL/02_TabloidMVC_Seed_Data.sql)
9. Click the execute with debugger solid green button to launch the app
10. Log into the website using “admin@example.com” if greeted with a login page
11. From the home page, click the “CATEGORY MANAGEMENT” option in the navbar
12. You should be redirected to a page with all available categories listed. Click the “New Category” button
13. You will be redirected to a page that will allow you to input text to create a new category.
14. If you enter text for a new category and hit create, you will be redirected  back to the category list, and your new category will be added to the list in the appropriate spot (alphabetical order)
15. If you Select the “back to list” option, your category will not be created, and you will be redirected  back to the category list.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

2022-11-01 14:49 UTC, sarahebrooks12 requested changes
Please include list of all categories in alphabetical order in testing instructions so we can verify we are getting the correct information from the database

2022-11-01 19:30 UTC, CaraNetzer approved these changes
Tested and working!

2022-11-02 13:27 UTC, sarahebrooks12 approved these changes

2022-11-02 13:52 UTC, Trey-Chambers approved these changes
Tested and working

2022-11-02 14:06 UTC, merged